version: '3.6'

networks:
  car_directory:
    name: car_directory


services:
  postgres:
    container_name: db.local
    build:
      dockerfile: provision/docker/postgres/Dockerfile
    image: car-directory-db:latest
    env_file:
      - provision/env/postgres.env
    volumes:
      - ./provision/docker/postgres/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - car_directory

  backend:
    container_name: backend.local
    build:
      dockerfile: provision/docker/backend/Dockerfile
    image: car-directory-backend:latest
    env_file:
      - provision/env/postgres.env
      - provision/env/backend.env
    volumes:
      - ./backend:/source
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - car_directory
