server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: car-directory

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:car_directory}
    username: ${POSTGRES_USER:car_directory}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

      format_sql: true

    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: ${POSTGRES_DEFAULT_SCHEMA}

logging:
  level:
    org.hibernate.SQL: debug
