server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: car-directory

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_DATABASE:car_directory}
    username: ${DB_USER_USERNAME:car_directory}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

      format_sql: true

    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: car_directory
logging:
  level:
    org.hibernate.SQL: debug
