FROM postgres:latest

ENV POSTGRES_USER=car_directory \
    POSTGRES_DB=car_directory \
    POSTGRES_PASSWORD=StrongPassword123! \
    POSTGRES_DEFAULT_SCHEMA=car_directory

VOLUME ["/docker-entrypoint-initdb.d"]
